services:
  db:
    image: postgres:16-alpine
    container_name: slideit-db
    environment:
      POSTGRES_USER: slideit_user
      POSTGRES_PASSWORD: slideit_password
      POSTGRES_DB: slideit_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: