### 1. Créer le Coach de Surf
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "nom": "Slater",
  "prenom": "Kelly",
  "email": "kelly.coach@slideit.com",
  "role": "MONITEUR",
  "telephone": "0611223344"
}

###

### 2. Créer l'Élève
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean.eleve@email.com",
  "role": "ELEVE",
  "telephone": "0601020304"
}

###

### 3. Planifier la Session de Surf
POST http://localhost:8080/api/sessions
Content-Type: application/json

{
  "discipline": "SURF",
  "dateHeureDebut": "2026-06-01T10:00:00",
  "dateHeureFin": "2026-06-01T12:00:00",
  "statut": "PLANIFIEE",
  "coach": { "id": 1 },
  "eleve": { "id": 2 }
}

### 4. Planifier la Session de skate
POST http://localhost:8080/api/sessions
Content-Type: application/json

{
  "discipline": "SKATE",
  "dateHeureDebut": "2026-06-01T10:00:00",
  "dateHeureFin": "2026-06-01T12:00:00",
  "statut": "PLANIFIEE",
  "coach": { "id": 1 },
  "eleve": { "id": 2 }
}

### Inscription d'un nouvel élève
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nom": "Dupont",
  "prenom": "Jean",
  "email": "jean.dupont@gmail.com",
  "password": "monSuperMotDePasse123",
  "role": "MONITEUR",
  "telephone": "0601020304"
}

### Login d'un élève
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "jean.dupont@gmail.com",
"password": "monSuperMotDePasse123"
}

###
GET http://localhost:8080/api/users
Content-Type: application/json